language: go

os:
  - windows

go:
  - 1.11.x

before_script:
  # in git-bash download com0com
  - curl -fsSL https://sourceforge.net/projects/com0com/files/latest/download -o com0com.zip
  - 7z e com0com.zip *x64*.exe
  - mv *x64*.exe com0com-setup.exe
  # use cmd.exe to execute install.bat
  - powershell -c start -verb runas cmd '/C start /D "%V" .install.bat'
  # back to git-bash
  - sleep 10
  - export GO111MODULE=on
  - make ensure

script:
  - make style_check
  - make test ARGS="-i=COM10 -o=COM11"

after_success:
  - bash <(curl -s https://codecov.io/bash)
