sudo: required
language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.11.x

matrix:
  allow_failures:
    - os: windows

addons:
  homebrew:
    update: true
    packages:
    - socat
  apt:
    update: true
    packages:
    - socat

install:
  - source ./.travis/install.sh

before_script:
  - export GO111MODULE=on
  - export SHELL=/bin/bash # for windows make
  - make ensure

script:
  - make style_check
  - make test ARGS="-i=${TEST_INPUT_PTY} -o=${TEST_OUTPUT_PTY}"

after_success:
  - bash <(curl -s https://codecov.io/bash)
